/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conductor_page;

import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author ELCOT
 */
public class conductor_entry extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(conductor_entry.class.getName());

    /**
     * Creates new form conductor_entry
     */
    private boolean isLoading = true;
     private int conductorId;
    private String fullName;
    public conductor_entry(){
        initComponents();
        screen.setOpaque(false);
    }

    public conductor_entry(int conductorId, String fullName) {
        this.conductorId = conductorId;
        this.fullName = fullName;
        initComponents();
        conductor_name_update.setText(fullName);
        conductor_empid_update.setText(String.valueOf(conductorId));
        screen.setOpaque(false);
            isLoading = false;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        screen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bus_no_input = new javax.swing.JTextField();
        conductor_name_update = new javax.swing.JLabel();
        enter = new javax.swing.JButton();
        emp_id = new javax.swing.JLabel();
        conductor_empid_update = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 560));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        screen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("WELCOME TO THE CONDUCTOR PAGE");
        screen.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("NAME");
        screen.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("BUS NO");
        screen.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        bus_no_input.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        screen.add(bus_no_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 140, 40));

        conductor_name_update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        screen.add(conductor_name_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 130, 30));

        enter.setBackground(new java.awt.Color(102, 102, 255));
        enter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        enter.setForeground(new java.awt.Color(255, 255, 255));
        enter.setText("ENTER");
        enter.addActionListener(this::enterActionPerformed);
        screen.add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        emp_id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        emp_id.setText("EMP ID");
        screen.add(emp_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        conductor_empid_update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        screen.add(conductor_empid_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 130, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus_route_booking/images/back-button.png"))); // NOI18N
        jButton2.addActionListener(this::jButton2ActionPerformed);
        screen.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(screen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 560));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conductor_page/bus-background.jpg"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(1280, 560));
        background.setMinimumSize(new java.awt.Dimension(1280, 560));
        background.setPreferredSize(new java.awt.Dimension(1280, 560));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        // TODO add your handling code here:
        if (isLoading) return;
        String busNumber = bus_no_input.getText().trim();

    if (busNumber.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter bus number");
        return;
    }

    try {
        Connection conn = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/bus_booking_db", "root", "password");

        CallableStatement cs = conn.prepareCall(
            "{CALL sp_conductor_get_assignment(?, ?, ?, ?, ?, ?)}");
        cs.setInt(1, conductorId);
        cs.setString(2, busNumber);
        cs.registerOutParameter(3, Types.INTEGER);
        cs.registerOutParameter(4, Types.INTEGER);
        cs.registerOutParameter(5, Types.VARCHAR);
        cs.registerOutParameter(6, Types.INTEGER);
        cs.execute();

        int assignmentId = cs.getInt(3);
        boolean wasNull = cs.wasNull();

        if (wasNull || assignmentId == 0) {
            JOptionPane.showMessageDialog(this,
                "Invalid bus number or you are not assigned to this bus today");
            cs.close();
            conn.close();
            return;
        }

        int scheduleId = cs.getInt(4);
        String routeName = cs.getString(5);
        int routeId = cs.getInt(6);

        cs.close();
        conn.close();

        JOptionPane.showMessageDialog(this, "Bus Verified: " + routeName);

        conductor_main frame = new conductor_main(
            conductorId, assignmentId, scheduleId, routeId, routeName, busNumber);
        frame.setVisible(true);
        this.dispose();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
    }
       
    }//GEN-LAST:event_enterActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         conductor_login frame=new conductor_login();
        frame.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new conductor_entry().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField bus_no_input;
    private javax.swing.JLabel conductor_empid_update;
    private javax.swing.JLabel conductor_name_update;
    private javax.swing.JLabel emp_id;
    private javax.swing.JButton enter;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel screen;
    // End of variables declaration//GEN-END:variables
}
