/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package user;
import bus_route_booking.images.common_login;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.*;
import java.awt.event.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
/**
 *
 * @author ELCOT
 */
public class user_local extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(user_local.class.getName());

    /**
     * Creates new form user_local
     */
    private JPopupMenu fromSuggestions = new JPopupMenu();
private JPopupMenu toSuggestions = new JPopupMenu();

    public user_local() {
        initComponents();
        resultpanel.setLayout(new javax.swing.BoxLayout(resultpanel, javax.swing.BoxLayout.Y_AXIS));
        

    lstFromSuggestions.setVisible(false);
    lstToSuggestions.setVisible(false);
        
        
        setupAutoSuggest(txtFrom, lstFromSuggestions);  // ← txtFrom must match exact variable name
    setupAutoSuggest(txtTo, lstToSuggestions); 
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        txtFrom = new javax.swing.JTextField();
        txtTo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstToSuggestions = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstFromSuggestions = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultpanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setText("welcome ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 5));
        jPanel1.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("SEARCH ROUTES");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 19, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("FROM");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 71, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("TO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 71, -1, -1));

        search.setBackground(new java.awt.Color(255, 51, 51));
        search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("search");
        search.addActionListener(this::searchActionPerformed);
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 103, 94, -1));

        txtFrom.addActionListener(this::txtFromActionPerformed);
        jPanel1.add(txtFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 75, 148, -1));
        jPanel1.add(txtTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 75, 150, -1));

        lstToSuggestions.setBorder(null);
        lstToSuggestions.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstToSuggestions);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 103, 148, 52));

        lstFromSuggestions.setBorder(null);
        lstFromSuggestions.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lstFromSuggestions);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 103, 148, 52));

        jScrollPane1.setBorder(null);

        javax.swing.GroupLayout resultpanelLayout = new javax.swing.GroupLayout(resultpanel);
        resultpanel.setLayout(resultpanelLayout);
        resultpanelLayout.setHorizontalGroup(
            resultpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        resultpanelLayout.setVerticalGroup(
            resultpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(resultpanel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 600, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 940, 500));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus_route_booking/images/back-button.png"))); // NOI18N
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user/local-pg (1).png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 560));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 560));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents


private void setupAutoSuggest(JTextField textField, JList suggestionList) {

    DefaultListModel<String> model = new DefaultListModel<>();
    suggestionList.setModel(model);
    suggestionList.setVisible(false);

    final boolean[] suppress = {false};

    textField.getDocument().addDocumentListener(new DocumentListener() {

        public void insertUpdate(DocumentEvent e) { updateList(); }
        public void removeUpdate(DocumentEvent e) { updateList(); }
        public void changedUpdate(DocumentEvent e) { updateList(); }

        private void updateList() {

            if (suppress[0]) return;

            String typed = textField.getText().trim();
            model.clear();

            if (typed.isEmpty()) {
                suggestionList.setVisible(false);
                suggestionList.getParent().revalidate();
                suggestionList.getParent().repaint();
                return;
            }

            try {
                Connection conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/bus_booking_db", "root", "password");

                PreparedStatement ps = conn.prepareStatement(
                    "SELECT stop_name FROM shared_stop WHERE stop_name LIKE ? LIMIT 5");
                ps.setString(1, typed + "%");
                ResultSet rs = ps.executeQuery();

                while (rs.next()) {
                    model.addElement(rs.getString("stop_name"));
                }

                ps.close();
                conn.close();

                if (model.size() > 0) {
                    suggestionList.setVisible(true);
                } else {
                    suggestionList.setVisible(false);
                }

                suggestionList.getParent().revalidate();
                suggestionList.getParent().repaint();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "DB Error: " + ex.getMessage());
            }
        }
    });

    suggestionList.addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting() && suggestionList.getSelectedValue() != null) {
            suppress[0] = true;
            textField.setText(suggestionList.getSelectedValue().toString());
            suggestionList.setVisible(false);
            suggestionList.getParent().revalidate();
            suggestionList.getParent().repaint();
            suppress[0] = false;
        }
    });
}
   

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        

    String fromStop = txtFrom.getText().trim();
    String toStop = txtTo.getText().trim();

    System.out.println("Searching: " + fromStop + " to " + toStop); // debug

    if (fromStop.isEmpty() || toStop.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter both From and To stops");
        return;
    }

    if (!isValidStop(fromStop)) {
        JOptionPane.showMessageDialog(this, "Please select a valid From stop from the list");
        return;
    }

    if (!isValidStop(toStop)) {
        JOptionPane.showMessageDialog(this, "Please select a valid To stop from the list");
        return;
    }

    resultpanel.removeAll();

    try {
        Connection conn = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/bus_booking_db", "root", "password");

        // ===== GET STOP IDs FIRST =====
        int fromStopId = getStopId(conn, fromStop);
        int toStopId = getStopId(conn, toStop);

        System.out.println("From ID: " + fromStopId + " To ID: " + toStopId); // debug

        if (fromStopId == -1 || toStopId == -1) {
            JOptionPane.showMessageDialog(this, "Stop not found in database");
            conn.close();
            return;
        }

        // ===== DIRECT BUSES =====
        String directSql = "SELECT * FROM v_local_direct_routes " +
                "WHERE from_stop_id = ? AND to_stop_id = ? " +
                "ORDER BY departure_time";

        PreparedStatement ps = conn.prepareStatement(directSql);
        ps.setInt(1, fromStopId);
        ps.setInt(2, toStopId);
        ResultSet rs = ps.executeQuery();

        boolean hasDirect = false;

        while (rs.next()) {

            if (!hasDirect) {
                JLabel header = new JLabel("  Direct Buses");
                header.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
                header.setForeground(new java.awt.Color(0, 120, 0));
                resultpanel.add(header);
                resultpanel.add(javax.swing.Box.createVerticalStrut(6));
                hasDirect = true;
            }

            int scheduleId      = rs.getInt("schedule_id");
            String busNumber    = rs.getString("bus_number");
            String busType      = rs.getString("bus_type");
            String routeNumber  = rs.getString("route_number");
            String depTime      = rs.getString("departure_time");
            String arrTime      = rs.getString("arrival_time");
            double fare         = rs.getDouble("fare");

            String label = "<html>" +
                    "<b>" + busNumber + "</b> (" + busType + ")&nbsp;&nbsp;Route: " + routeNumber + "<br>" +
                    "Departure: " + depTime + "&nbsp;&nbsp;Arrival: " + arrTime +
                    "&nbsp;&nbsp;<b>Fare: Rs." + fare + "</b>" +
                    "</html>";

            JButton btn = new JButton(label);
            btn.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
            btn.setMaximumSize(new java.awt.Dimension(Short.MAX_VALUE, 60));
            btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

            final int sid = scheduleId;
            btn.addActionListener(e -> {
               
                bus_route frame = new bus_route(sid, busNumber, fromStop, toStop);
                frame.setVisible(true);
                
            });

            resultpanel.add(btn);
            resultpanel.add(javax.swing.Box.createVerticalStrut(6));
        }

        ps.close();
        rs.close();

        if (!hasDirect) {
            JLabel noDirect = new JLabel("  No direct buses found");
            noDirect.setForeground(java.awt.Color.RED);
            resultpanel.add(noDirect);
            resultpanel.add(javax.swing.Box.createVerticalStrut(10));
        }

        // ===== CONNECTING BUSES =====
        CallableStatement cs = conn.prepareCall("{CALL sp_local_connecting_buses(?, ?, ?)}");
        cs.setInt(1, fromStopId);
        cs.setInt(2, toStopId);

        // get current day name
        String day = new java.text.SimpleDateFormat("EEE").format(new java.util.Date());
        cs.setString(3, day);

        ResultSet crs = cs.executeQuery();

        boolean hasConnecting = false;

        while (crs.next()) {

            if (!hasConnecting) {
                JLabel header2 = new JLabel("  Connecting Buses");
                header2.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
                header2.setForeground(new java.awt.Color(0, 0, 180));
                resultpanel.add(header2);
                resultpanel.add(javax.swing.Box.createVerticalStrut(6));
                hasConnecting = true;
            }

            String leg1Route    = crs.getString("leg1_route");
            String transferStop = crs.getString("transfer_stop");
            String leg1Depart   = crs.getString("leg1_depart");
            String leg1Arrive   = crs.getString("leg1_arrive");
            double leg1Fare     = crs.getDouble("leg1_fare");

            String leg2Route    = crs.getString("leg2_route");
            String alightStop   = crs.getString("alight_stop");
            String leg2Depart   = crs.getString("leg2_depart");
            String leg2Arrive   = crs.getString("leg2_arrive");
            double leg2Fare     = crs.getDouble("leg2_fare");

            double totalFare    = crs.getDouble("total_fare");

            String label = "<html>" +
    "<b>Leg 1:</b> " + leg1Route +
    " | " + fromStop  + " → " + transferStop +
    " | Dep: " + leg1Depart + " Arr: " + leg1Arrive +
    " | Rs." + leg1Fare + "<br>" +
    "<b>Transfer at:</b> " + transferStop + "<br>" +
    "<b>Leg 2:</b> " + leg2Route +
    " | " + transferStop + " → " + alightStop +
    " | Dep: " + leg2Depart + " Arr: " + leg2Arrive +
    " | Rs." + leg2Fare + "<br>" +
    "<b>Total Fare: Rs." + totalFare + "</b>" +
    "</html>";

            JButton btn2 = new JButton(label);
            btn2.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
            btn2.setMaximumSize(new java.awt.Dimension(Short.MAX_VALUE, 100));
            btn2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

            resultpanel.add(btn2);
            resultpanel.add(javax.swing.Box.createVerticalStrut(6));
        }

        if (!hasConnecting) {
            JLabel noConn = new JLabel("  No connecting buses found");
            noConn.setForeground(java.awt.Color.RED);
            resultpanel.add(noConn);
        }

        cs.close();
        conn.close();

        resultpanel.revalidate();
        resultpanel.repaint();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
        e.printStackTrace();
    }
    }
    private int getStopId(Connection conn, String stopName) throws SQLException {
    PreparedStatement ps = conn.prepareStatement(
        "SELECT stop_id FROM shared_stop WHERE stop_name = ?");
    ps.setString(1, stopName);
    ResultSet rs = ps.executeQuery();
    int id = -1;
    if (rs.next()) {
        id = rs.getInt("stop_id");
    }
    ps.close();
    return id;
}

private boolean isValidStop(String stopName) {
    try {
        Connection conn = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/bus_booking_db", "root", "password");
        PreparedStatement ps = conn.prepareStatement(
            "SELECT stop_id FROM shared_stop WHERE stop_name = ?");
        ps.setString(1, stopName);
        ResultSet rs = ps.executeQuery();
        boolean exists = rs.next();
        ps.close();
        conn.close();
        return exists;
    } catch (SQLException ex) {
        return false;
    }

         
    }//GEN-LAST:event_searchActionPerformed

    private void txtFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFromActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         common_login frame=new common_login();
        frame.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new user_local().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lstFromSuggestions;
    private javax.swing.JList<String> lstToSuggestions;
    private javax.swing.JPanel resultpanel;
    private javax.swing.JButton search;
    private javax.swing.JTextField txtFrom;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
